vim.keymap.set("n", "]b", ":bnext<CR>", { desc = "Buffer Next" })
vim.keymap.set("n", "[b", ":bprevious<CR>", { desc = "Buffer Previous" })
vim.keymap.set("n", "<leader>bn", ":bnext<CR>", { desc = "Buffer Next" })
vim.keymap.set("n", "<leader>bp", ":bprevious<CR>", { desc = "Buffer Previous" })
vim.keymap.set("n", "<leader>bd", ":bdelete<CR>", { desc = "Buffer Delete" })
